#file: noinspection YAMLSchemaValidation
name: ${projectName}
main: ${projectGroup}.${projectType}.${projectName}Plugin
version: ${projectVersion}
authors: ${projectAuthors}
api-version: ${paperApiVersion}
